server:
  port: 8080

spring:
  application:
    name: generator
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://172.22.11.250:5432/jdd2db?currentSchema=jdd2db
    username: jdd2db
    password: 123456
    hikari:
      pool-name: DATA-ACCUMULATION-CP
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 1800000

#指定接口包扫描
springdoc:
  packagesToScan: com.example.generator.web.controller
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#mybatis
mybatisPlus:
  mapperLocations: classpath:mapper/*.xml
  globalConfig:
    dbConfig:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #驼峰下划线转换
      table-underline: true
  configuration:
      use-actual-param-name: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

